### ISSUE TITLE
Meteor packages with `lazy:true` not working

### ISSUE THREAD

**Issue by afrokick** [Akryum/meteor-vite#2]
### Simple lazy package

**package.js**:

```
Package.describe({
  name: 'test:lazy',
  version: '0.0.1',
  summary: 'summary',
  git: 'https://github.com/Akryum/meteor-vite',
  documentation: 'README.md',
})

Package.onUse(function(api) {
  api.use('ecmascript')
  api.mainModule('index.js', ['client', 'server'], { lazy: true });
})
```

**index.js**:

```
export const A = 1;
```

add the package to your vite project:

`meteor add test:lazy`

Use it somewhere in your project:

**main.ts**:

```
import { A } from 'meteor/test:lazy'
```

### Result

Browser error:

`Uncaught SyntaxError: The requested module '/@id/__x00__meteor/test:lazy' does not provide an export named 'A'`

**Comment by afrokick** [comment]
As a workaround, you can import packages into Meteor's main.ts script. Then, Meteor compile it properly.

**Comment by afrokick** [comment]
Please, check module.exportDefault and module.link in reify readme https://github.com/benjamn/reify/blob/c9657a9fcb735b870c6c7ee6e95b1403517189e8/README.md#exports-that-are-really-imports

**Comment by Akryum** [comment]
> Please, check module.exportDefault and module.link in reify readme @Akryum [benjamn/reify@`c9657a9`/README.md#exports-that-are-really-imports](https://github.com/benjamn/reify/blob/c9657a9fcb735b870c6c7ee6e95b1403517189e8/README.md#exports-that-are-really-imports)

Fixed in https://github.com/Akryum/meteor-vite/commit/a592eacca3851ad3e05c2a6e940085f2c9d2c82a (v0.1.5)

**Comment by gunnartorfis** [comment]
I'm still seeing the following error: 
`Uncaught SyntaxError: The requested module '/@id/__x00__meteor/react-meteor-data' does not provide an export named 'useTracker'`

Environment:
- `vite:bundler` with unspecified version in my `packages` file
- Meteor 2.8.1
- React 18
- @vite/plugin-react: 3.1.0
- vite 4.1.1

**Comment by red-meadow** [comment]
I think, this issue #21 is the source of "The requested module..." error.
If you fork [react-meteor-data](https://github.com/meteor/react-packages/tree/master/packages/react-meteor-data) and add the line `export const A = 'A'`, it works.
![image](https://user-images.githubusercontent.com/38740713/217374873-bb475fbc-70d9-4fef-addd-74ee412fc980.png)
